"""add_knowledge_models_and_update_existing_models

Revision ID: 4fa97bb67d7c
Revises: 94947e70a876
Create Date: 2026-05-31 02:13:04.668403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa97bb67d7c'
down_revision: Union[str, Sequence[str], None] = '94947e70a876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('customer_email', sa.String(length=200), nullable=True))
    op.drop_column('knowledge_chunks', 'qdrant_point_id')
    # ### end Alembic commands ###

    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Add embedding column to knowledge_chunks
    op.add_column('knowledge_chunks', sa.Column('embedding', sa.Text(), nullable=True))

    # Change embedding column to actual vector type after creation
    op.execute("ALTER TABLE knowledge_chunks ALTER COLUMN embedding TYPE vector(1536) USING embedding::vector")

    # IVFFlat index for fast ANN search
    op.execute(
        "CREATE INDEX knowledge_chunks_embedding_idx "
        "ON knowledge_chunks USING ivfflat (embedding vector_cosine_ops) "
        "WITH (lists = 100)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('qdrant_point_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('conversations', 'customer_email')
    # ### end Alembic commands ###
